name: 4-event-triggers
on: workflow_dispatch
# [push, pull_request]
#     push:
#         branches:
#             - 'devbranch'
# on:
#     schedule:
#       - cron: "*/1 0 * * *"
jobs:
    dev-branch-event-trigger-job:
        name: dev branch event trigger
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world"