name: 5-actions
on: workflow_dispatch
jobs:
  jave-first-job:
    name: java installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: '21'
      - run: echo "java installation"
      - run: ls -l
      - run: mvn build